include:
  package:pedantic/analysis_options.yaml

linter:
  - rules:
      - annotate_overrides
      - always_put_required_named_parameters_first
      - avoid_print
      - avoid_returning_null
      - avoid_returning_null_for_future
      - avoid_returning_this
      - avoid_unused_constructor_parameters
      - await_only_futures
      - camel_case_types
      - cancel_subscriptions
      - close_sinks
      - comment_references
      - constant_identifier_names
      - control_flow_in_finally
      - empty_constructor_bodies
      - empty_statements
      - non_constant_identifier_names
      - prefer_const_constructors_in_immutables
      - prefer_const_declarations
      - prefer_const_literals_to_create_immutables
      - sort_constructors_first
      - sort_unnamed_constructors_first
      - unnecessary_const
      - unawaited_futures
      - use_setters_to_change_properties